#!/usr/bin/env python3
"""
publish_versions.py
===================
CLI script for the version-publisher skill.
Processes sequential version directories, renames files to PascalCase (preserving acronyms),
runs claret-generator.jar, commits/pushes to GitHub branch, creates tag and release.
"""

import os
import sys
import argparse
import shutil
from pathlib import Path

# Add project root scripts to sys.path
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from claret_engine import (
    to_pascal_case_with_acronyms,
    format_version,
    format_branch_title,
    run_claret_generator,
    GitHubManager,
    get_default_repo,
    logger
)

def process_and_publish_versions(
    version_dirs: list,
    branch_name: str,
    repo: str,
    coverage: str = "gt",
    formats: str = "all",
    dry_run: bool = False
):
    gh = GitHubManager(repo=repo)
    # The integrator/merging directory name is identical to the branch name
    integrator_dir = PROJECT_ROOT.parent / branch_name if not (PROJECT_ROOT / branch_name).exists() else (PROJECT_ROOT / branch_name)
    integrator_dir.mkdir(parents=True, exist_ok=True)

    total = len(version_dirs)
    logger.info(f"Starting version publication for {total} versions on branch '{branch_name}' (Repo: {repo})")
    logger.info(f"Main integrator/merging directory: '{integrator_dir}' (preserves and merges state across loop iterations)")

    for idx, v_entry in enumerate(version_dirs, start=1):
        v_path = Path(v_entry)
        if not v_path.is_absolute():
            # Check relative to parent workspace
            if (PROJECT_ROOT.parent / v_entry).exists():
                v_path = PROJECT_ROOT.parent / v_entry
            elif (PROJECT_ROOT / v_entry).exists():
                v_path = PROJECT_ROOT / v_entry

        if not v_path.exists():
            logger.error(f"Version directory not found: {v_entry}")
            continue

        ver_str = format_version(idx)
        tag_name = f"{branch_name}_v{ver_str}"
        release_title = f"{format_branch_title(branch_name)} v{ver_str}"

        logger.info(f"\n=======================================================")
        logger.info(f"[{idx}/{total}] Merging version directory: {v_path.name} into '{branch_name}' -> Version {ver_str}")
        logger.info(f"Tag: {tag_name} | Release: {release_title}")
        logger.info(f"=======================================================")

        # 1. Search and merge .claret and .dsl files with PascalCase renaming into integrator_dir
        found_files = 0
        for root_p, _, files in os.walk(v_path):
            for file in files:
                if file.endswith(".claret") or file.endswith(".dsl"):
                    src_file = Path(root_p) / file
                    new_name = to_pascal_case_with_acronyms(file)
                    dest_file = integrator_dir / new_name
                    shutil.copy2(src_file, dest_file)
                    logger.debug(f"Merged & renamed: {file} -> {dest_file}")
                    found_files += 1

        logger.info(f"Merged {found_files} specification files from '{v_path.name}' into integrator directory '{integrator_dir}'.")

        # 3. Run claret-generator.jar
        success, output = run_claret_generator(
            input_dir=integrator_dir,
            output_dir=integrator_dir / "output",
            formats=formats,
            coverage=coverage
        )

        if not success:
            logger.error(f"Generation failed for version {ver_str}. Stopping.")
            break

        # 4. Commit, Push, Tag & Release
        if dry_run:
            logger.info(f"[DRY-RUN] Would commit, push to branch '{branch_name}', create tag '{tag_name}', and release '{release_title}'.")
        else:
            commit_msg = f"feat({branch_name}): publish specification and test suite v{ver_str}"
            gh.add_commit_push(repo_dir=integrator_dir, branch=branch_name, commit_message=commit_msg)
            gh.create_tag(repo_dir=integrator_dir, tag_name=tag_name, message=f"Release {release_title}")
            gh.create_release(tag_name=tag_name, release_title=release_title, body=f"Automated release of {release_title} generated by CLARET Versionador.")

    logger.info("All version directories processed successfully.")

def main():
    parser = argparse.ArgumentParser(description="Publish sequential CLARET version specifications.")
    parser.add_argument("--version-dirs", nargs="+", required=True, help="List of version directories to process")
    parser.add_argument("--branch", required=True, help="Target GitHub branch / integrator directory")
    parser.add_argument("--repo", default=get_default_repo(), help="GitHub repository (owner/repo)")
    parser.add_argument("--coverage", default="gt", choices=["gt", "gtp", "art", "complete", "basic-only", "all-branches"], help="Coverage approach")
    parser.add_argument("--formats", default="all", help="Output formats (all, xlsx, txt, docx, odt, xml, tgf, alts)")
    parser.add_argument("--dry-run", action="store_true", help="Simulate without pushing to GitHub")

    args = parser.parse_args()
    process_and_publish_versions(
        version_dirs=args.version_dirs,
        branch_name=args.branch,
        repo=args.repo,
        coverage=args.coverage,
        formats=args.formats,
        dry_run=args.dry_run
    )

if __name__ == "__main__":
    main()
